services:
  - type: web
    name: drawmatch-beta
    runtime: python
    plan: free
    buildCommand: "python3 -m py_compile server.py"
    startCommand: "python3 server.py"
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: GOOGLE_CLIENT_ID
        value: 44763469278-3a32q6v9ddbbcusqukd2utr1aep1ssli.apps.googleusercontent.com
